/* 
 * Platform
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IStickyNotesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create sticky note item
        /// </summary>
        /// <remarks>
        /// Adds a sticky note item to a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to create the item.</param>
        /// <returns>StickyNoteItem</returns>
        StickyNoteItem CreateStickyNoteItem (StickyNoteCreateRequest body, string boardId);

        /// <summary>
        /// Create sticky note item
        /// </summary>
        /// <remarks>
        /// Adds a sticky note item to a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to create the item.</param>
        /// <returns>ApiResponse of StickyNoteItem</returns>
        ApiResponse<StickyNoteItem> CreateStickyNoteItemWithHttpInfo (StickyNoteCreateRequest body, string boardId);
        /// <summary>
        /// Delete sticky note item
        /// </summary>
        /// <remarks>
        /// Deletes a sticky note item from the board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 3&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to delete the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to delete.</param>
        /// <returns>Object</returns>
        Object DeleteStickyNoteItem (string boardId, string itemId);

        /// <summary>
        /// Delete sticky note item
        /// </summary>
        /// <remarks>
        /// Deletes a sticky note item from the board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 3&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to delete the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to delete.</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> DeleteStickyNoteItemWithHttpInfo (string boardId, string itemId);
        /// <summary>
        /// Get sticky note item
        /// </summary>
        /// <remarks>
        /// Retrieves information for a specific sticky note item on a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:read&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 1&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to retrieve a specific item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to retrieve.</param>
        /// <returns>StickyNoteItem</returns>
        StickyNoteItem GetStickyNoteItem (string boardId, string itemId);

        /// <summary>
        /// Get sticky note item
        /// </summary>
        /// <remarks>
        /// Retrieves information for a specific sticky note item on a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:read&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 1&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to retrieve a specific item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to retrieve.</param>
        /// <returns>ApiResponse of StickyNoteItem</returns>
        ApiResponse<StickyNoteItem> GetStickyNoteItemWithHttpInfo (string boardId, string itemId);
        /// <summary>
        /// Update sticky note item
        /// </summary>
        /// <remarks>
        /// Updates a sticky note item on a board based on the data and style properties provided in the request body.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to update the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to update.</param>
        /// <returns>StickyNoteItem</returns>
        StickyNoteItem UpdateStickyNoteItem (StickyNoteUpdateRequest body, string boardId, string itemId);

        /// <summary>
        /// Update sticky note item
        /// </summary>
        /// <remarks>
        /// Updates a sticky note item on a board based on the data and style properties provided in the request body.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to update the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to update.</param>
        /// <returns>ApiResponse of StickyNoteItem</returns>
        ApiResponse<StickyNoteItem> UpdateStickyNoteItemWithHttpInfo (StickyNoteUpdateRequest body, string boardId, string itemId);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create sticky note item
        /// </summary>
        /// <remarks>
        /// Adds a sticky note item to a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to create the item.</param>
        /// <returns>Task of StickyNoteItem</returns>
        System.Threading.Tasks.Task<StickyNoteItem> CreateStickyNoteItemAsync (StickyNoteCreateRequest body, string boardId);

        /// <summary>
        /// Create sticky note item
        /// </summary>
        /// <remarks>
        /// Adds a sticky note item to a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to create the item.</param>
        /// <returns>Task of ApiResponse (StickyNoteItem)</returns>
        System.Threading.Tasks.Task<ApiResponse<StickyNoteItem>> CreateStickyNoteItemAsyncWithHttpInfo (StickyNoteCreateRequest body, string boardId);
        /// <summary>
        /// Delete sticky note item
        /// </summary>
        /// <remarks>
        /// Deletes a sticky note item from the board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 3&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to delete the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to delete.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> DeleteStickyNoteItemAsync (string boardId, string itemId);

        /// <summary>
        /// Delete sticky note item
        /// </summary>
        /// <remarks>
        /// Deletes a sticky note item from the board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 3&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to delete the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to delete.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteStickyNoteItemAsyncWithHttpInfo (string boardId, string itemId);
        /// <summary>
        /// Get sticky note item
        /// </summary>
        /// <remarks>
        /// Retrieves information for a specific sticky note item on a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:read&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 1&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to retrieve a specific item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to retrieve.</param>
        /// <returns>Task of StickyNoteItem</returns>
        System.Threading.Tasks.Task<StickyNoteItem> GetStickyNoteItemAsync (string boardId, string itemId);

        /// <summary>
        /// Get sticky note item
        /// </summary>
        /// <remarks>
        /// Retrieves information for a specific sticky note item on a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:read&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 1&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to retrieve a specific item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to retrieve.</param>
        /// <returns>Task of ApiResponse (StickyNoteItem)</returns>
        System.Threading.Tasks.Task<ApiResponse<StickyNoteItem>> GetStickyNoteItemAsyncWithHttpInfo (string boardId, string itemId);
        /// <summary>
        /// Update sticky note item
        /// </summary>
        /// <remarks>
        /// Updates a sticky note item on a board based on the data and style properties provided in the request body.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to update the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to update.</param>
        /// <returns>Task of StickyNoteItem</returns>
        System.Threading.Tasks.Task<StickyNoteItem> UpdateStickyNoteItemAsync (StickyNoteUpdateRequest body, string boardId, string itemId);

        /// <summary>
        /// Update sticky note item
        /// </summary>
        /// <remarks>
        /// Updates a sticky note item on a board based on the data and style properties provided in the request body.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to update the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to update.</param>
        /// <returns>Task of ApiResponse (StickyNoteItem)</returns>
        System.Threading.Tasks.Task<ApiResponse<StickyNoteItem>> UpdateStickyNoteItemAsyncWithHttpInfo (StickyNoteUpdateRequest body, string boardId, string itemId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class StickyNotesApi : IStickyNotesApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StickyNotesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StickyNotesApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StickyNotesApi"/> class
        /// </summary>
        /// <returns></returns>
        public StickyNotesApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StickyNotesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StickyNotesApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create sticky note item Adds a sticky note item to a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to create the item.</param>
        /// <returns>StickyNoteItem</returns>
        public StickyNoteItem CreateStickyNoteItem (StickyNoteCreateRequest body, string boardId)
        {
             ApiResponse<StickyNoteItem> localVarResponse = CreateStickyNoteItemWithHttpInfo(body, boardId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create sticky note item Adds a sticky note item to a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to create the item.</param>
        /// <returns>ApiResponse of StickyNoteItem</returns>
        public ApiResponse< StickyNoteItem > CreateStickyNoteItemWithHttpInfo (StickyNoteCreateRequest body, string boardId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling StickyNotesApi->CreateStickyNoteItem");
            // verify the required parameter 'boardId' is set
            if (boardId == null)
                throw new ApiException(400, "Missing required parameter 'boardId' when calling StickyNotesApi->CreateStickyNoteItem");

            var localVarPath = "/v2/boards/{board_id}/sticky_notes";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (boardId != null) localVarPathParams.Add("board_id", this.Configuration.ApiClient.ParameterToString(boardId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateStickyNoteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StickyNoteItem>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (StickyNoteItem) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StickyNoteItem)));
        }

        /// <summary>
        /// Create sticky note item Adds a sticky note item to a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to create the item.</param>
        /// <returns>Task of StickyNoteItem</returns>
        public async System.Threading.Tasks.Task<StickyNoteItem> CreateStickyNoteItemAsync (StickyNoteCreateRequest body, string boardId)
        {
             ApiResponse<StickyNoteItem> localVarResponse = await CreateStickyNoteItemAsyncWithHttpInfo(body, boardId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create sticky note item Adds a sticky note item to a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to create the item.</param>
        /// <returns>Task of ApiResponse (StickyNoteItem)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<StickyNoteItem>> CreateStickyNoteItemAsyncWithHttpInfo (StickyNoteCreateRequest body, string boardId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling StickyNotesApi->CreateStickyNoteItem");
            // verify the required parameter 'boardId' is set
            if (boardId == null)
                throw new ApiException(400, "Missing required parameter 'boardId' when calling StickyNotesApi->CreateStickyNoteItem");

            var localVarPath = "/v2/boards/{board_id}/sticky_notes";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (boardId != null) localVarPathParams.Add("board_id", this.Configuration.ApiClient.ParameterToString(boardId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateStickyNoteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StickyNoteItem>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (StickyNoteItem) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StickyNoteItem)));
        }

        /// <summary>
        /// Delete sticky note item Deletes a sticky note item from the board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 3&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to delete the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to delete.</param>
        /// <returns>Object</returns>
        public Object DeleteStickyNoteItem (string boardId, string itemId)
        {
             ApiResponse<Object> localVarResponse = DeleteStickyNoteItemWithHttpInfo(boardId, itemId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete sticky note item Deletes a sticky note item from the board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 3&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to delete the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to delete.</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > DeleteStickyNoteItemWithHttpInfo (string boardId, string itemId)
        {
            // verify the required parameter 'boardId' is set
            if (boardId == null)
                throw new ApiException(400, "Missing required parameter 'boardId' when calling StickyNotesApi->DeleteStickyNoteItem");
            // verify the required parameter 'itemId' is set
            if (itemId == null)
                throw new ApiException(400, "Missing required parameter 'itemId' when calling StickyNotesApi->DeleteStickyNoteItem");

            var localVarPath = "/v2/boards/{board_id}/sticky_notes/{item_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (boardId != null) localVarPathParams.Add("board_id", this.Configuration.ApiClient.ParameterToString(boardId)); // path parameter
            if (itemId != null) localVarPathParams.Add("item_id", this.Configuration.ApiClient.ParameterToString(itemId)); // path parameter
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Delete, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteStickyNoteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Delete sticky note item Deletes a sticky note item from the board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 3&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to delete the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to delete.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> DeleteStickyNoteItemAsync (string boardId, string itemId)
        {
             ApiResponse<Object> localVarResponse = await DeleteStickyNoteItemAsyncWithHttpInfo(boardId, itemId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete sticky note item Deletes a sticky note item from the board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 3&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to delete the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to delete.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteStickyNoteItemAsyncWithHttpInfo (string boardId, string itemId)
        {
            // verify the required parameter 'boardId' is set
            if (boardId == null)
                throw new ApiException(400, "Missing required parameter 'boardId' when calling StickyNotesApi->DeleteStickyNoteItem");
            // verify the required parameter 'itemId' is set
            if (itemId == null)
                throw new ApiException(400, "Missing required parameter 'itemId' when calling StickyNotesApi->DeleteStickyNoteItem");

            var localVarPath = "/v2/boards/{board_id}/sticky_notes/{item_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (boardId != null) localVarPathParams.Add("board_id", this.Configuration.ApiClient.ParameterToString(boardId)); // path parameter
            if (itemId != null) localVarPathParams.Add("item_id", this.Configuration.ApiClient.ParameterToString(itemId)); // path parameter
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Delete, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteStickyNoteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Get sticky note item Retrieves information for a specific sticky note item on a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:read&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 1&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to retrieve a specific item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to retrieve.</param>
        /// <returns>StickyNoteItem</returns>
        public StickyNoteItem GetStickyNoteItem (string boardId, string itemId)
        {
             ApiResponse<StickyNoteItem> localVarResponse = GetStickyNoteItemWithHttpInfo(boardId, itemId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get sticky note item Retrieves information for a specific sticky note item on a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:read&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 1&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to retrieve a specific item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to retrieve.</param>
        /// <returns>ApiResponse of StickyNoteItem</returns>
        public ApiResponse< StickyNoteItem > GetStickyNoteItemWithHttpInfo (string boardId, string itemId)
        {
            // verify the required parameter 'boardId' is set
            if (boardId == null)
                throw new ApiException(400, "Missing required parameter 'boardId' when calling StickyNotesApi->GetStickyNoteItem");
            // verify the required parameter 'itemId' is set
            if (itemId == null)
                throw new ApiException(400, "Missing required parameter 'itemId' when calling StickyNotesApi->GetStickyNoteItem");

            var localVarPath = "/v2/boards/{board_id}/sticky_notes/{item_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (boardId != null) localVarPathParams.Add("board_id", this.Configuration.ApiClient.ParameterToString(boardId)); // path parameter
            if (itemId != null) localVarPathParams.Add("item_id", this.Configuration.ApiClient.ParameterToString(itemId)); // path parameter
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetStickyNoteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StickyNoteItem>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (StickyNoteItem) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StickyNoteItem)));
        }

        /// <summary>
        /// Get sticky note item Retrieves information for a specific sticky note item on a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:read&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 1&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to retrieve a specific item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to retrieve.</param>
        /// <returns>Task of StickyNoteItem</returns>
        public async System.Threading.Tasks.Task<StickyNoteItem> GetStickyNoteItemAsync (string boardId, string itemId)
        {
             ApiResponse<StickyNoteItem> localVarResponse = await GetStickyNoteItemAsyncWithHttpInfo(boardId, itemId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get sticky note item Retrieves information for a specific sticky note item on a board.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:read&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 1&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="boardId">Unique identifier (ID) of the board from which you want to retrieve a specific item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to retrieve.</param>
        /// <returns>Task of ApiResponse (StickyNoteItem)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<StickyNoteItem>> GetStickyNoteItemAsyncWithHttpInfo (string boardId, string itemId)
        {
            // verify the required parameter 'boardId' is set
            if (boardId == null)
                throw new ApiException(400, "Missing required parameter 'boardId' when calling StickyNotesApi->GetStickyNoteItem");
            // verify the required parameter 'itemId' is set
            if (itemId == null)
                throw new ApiException(400, "Missing required parameter 'itemId' when calling StickyNotesApi->GetStickyNoteItem");

            var localVarPath = "/v2/boards/{board_id}/sticky_notes/{item_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (boardId != null) localVarPathParams.Add("board_id", this.Configuration.ApiClient.ParameterToString(boardId)); // path parameter
            if (itemId != null) localVarPathParams.Add("item_id", this.Configuration.ApiClient.ParameterToString(itemId)); // path parameter
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetStickyNoteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StickyNoteItem>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (StickyNoteItem) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StickyNoteItem)));
        }

        /// <summary>
        /// Update sticky note item Updates a sticky note item on a board based on the data and style properties provided in the request body.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to update the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to update.</param>
        /// <returns>StickyNoteItem</returns>
        public StickyNoteItem UpdateStickyNoteItem (StickyNoteUpdateRequest body, string boardId, string itemId)
        {
             ApiResponse<StickyNoteItem> localVarResponse = UpdateStickyNoteItemWithHttpInfo(body, boardId, itemId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update sticky note item Updates a sticky note item on a board based on the data and style properties provided in the request body.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to update the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to update.</param>
        /// <returns>ApiResponse of StickyNoteItem</returns>
        public ApiResponse< StickyNoteItem > UpdateStickyNoteItemWithHttpInfo (StickyNoteUpdateRequest body, string boardId, string itemId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling StickyNotesApi->UpdateStickyNoteItem");
            // verify the required parameter 'boardId' is set
            if (boardId == null)
                throw new ApiException(400, "Missing required parameter 'boardId' when calling StickyNotesApi->UpdateStickyNoteItem");
            // verify the required parameter 'itemId' is set
            if (itemId == null)
                throw new ApiException(400, "Missing required parameter 'itemId' when calling StickyNotesApi->UpdateStickyNoteItem");

            var localVarPath = "/v2/boards/{board_id}/sticky_notes/{item_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (boardId != null) localVarPathParams.Add("board_id", this.Configuration.ApiClient.ParameterToString(boardId)); // path parameter
            if (itemId != null) localVarPathParams.Add("item_id", this.Configuration.ApiClient.ParameterToString(itemId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Patch, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateStickyNoteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StickyNoteItem>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (StickyNoteItem) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StickyNoteItem)));
        }

        /// <summary>
        /// Update sticky note item Updates a sticky note item on a board based on the data and style properties provided in the request body.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to update the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to update.</param>
        /// <returns>Task of StickyNoteItem</returns>
        public async System.Threading.Tasks.Task<StickyNoteItem> UpdateStickyNoteItemAsync (StickyNoteUpdateRequest body, string boardId, string itemId)
        {
             ApiResponse<StickyNoteItem> localVarResponse = await UpdateStickyNoteItemAsyncWithHttpInfo(body, boardId, itemId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update sticky note item Updates a sticky note item on a board based on the data and style properties provided in the request body.&lt;br/&gt;&lt;h3&gt;Required scope&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/scopes\&quot;&gt;boards:write&lt;/a&gt; &lt;br/&gt;&lt;h3&gt;Rate limiting&lt;/h3&gt; &lt;a target&#x3D;\&quot;blank\&quot; href&#x3D;\&quot;/reference/ratelimiting\&quot;&gt;Level 2&lt;/a&gt;&lt;br/&gt;
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="boardId">Unique identifier (ID) of the board where you want to update the item.</param>
        /// <param name="itemId">Unique identifier (ID) of the item that you want to update.</param>
        /// <returns>Task of ApiResponse (StickyNoteItem)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<StickyNoteItem>> UpdateStickyNoteItemAsyncWithHttpInfo (StickyNoteUpdateRequest body, string boardId, string itemId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling StickyNotesApi->UpdateStickyNoteItem");
            // verify the required parameter 'boardId' is set
            if (boardId == null)
                throw new ApiException(400, "Missing required parameter 'boardId' when calling StickyNotesApi->UpdateStickyNoteItem");
            // verify the required parameter 'itemId' is set
            if (itemId == null)
                throw new ApiException(400, "Missing required parameter 'itemId' when calling StickyNotesApi->UpdateStickyNoteItem");

            var localVarPath = "/v2/boards/{board_id}/sticky_notes/{item_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (boardId != null) localVarPathParams.Add("board_id", this.Configuration.ApiClient.ParameterToString(boardId)); // path parameter
            if (itemId != null) localVarPathParams.Add("item_id", this.Configuration.ApiClient.ParameterToString(itemId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (bearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Patch, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateStickyNoteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StickyNoteItem>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (StickyNoteItem) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StickyNoteItem)));
        }

    }
}
